### ISSUE TITLE
Suggestion: implement lazyListState.animateScroll

### ISSUE THREAD

**Issue by ArleyPereira** [Ahmad-Hamwi/TabSync#7]
A suggestion: Why not implement lazyListState.animateScroll instead of lazyListState.animateScrollToItem ? This way it would be possible to control the duration of the scroll, making it smoother.

With the help of ChatGPT I wrote a version implementing animateScroll and it seems to work just fine. I could only implement using a fixed height, dynamic would be better

```
@Stable
class TabSyncState(
    var selectedTabIndex: Int,
    var lazyListState: LazyListState,
    private var coroutineScope: CoroutineScope,
    private var syncedIndices: List<Int>,
    private var smoothScroll: Boolean,
    private var density: Density
) {
    private var previousTabIndex = selectedTabIndex

    operator fun component1(): Int = selectedTabIndex

    operator fun component2(): (Int) -> Unit = {
        require(it <= syncedIndices.size - 1) {
            "The selected tab's index is out of the bounds of the syncedIndices list provided. " +
                    "Either add an index to syncedIndices that corresponds to an item to your lazy list, " +
                    "or remove your excessive tab"
        }


        val newTabIndex = it
        val oldTabIndex = selectedTabIndex

        selectedTabIndex = newTabIndex
        previousTabIndex = oldTabIndex

        coroutineScope.launch {
            if (smoothScroll) {
                val itemSize = 286.dp
                val itemSizePx = with(density) { itemSize.toPx() }
                
                val deltaIndex = newTabIndex - oldTabIndex
                val distanceToScroll = deltaIndex * itemSizePx
                
                lazyListState.animateScrollBy(
                    value = distanceToScroll,
                    animationSpec = tween(durationMillis = 1000)
                )
            } else {
                lazyListState.scrollToItem(syncedIndices[newTabIndex])
            }
        }
    }

    operator fun component3(): LazyListState = lazyListState
}
```

**Comment by Ahmad-Hamwi** [comment]
Hi there.

If you look closley into the implementation of `animateScrollToItem`, you will find many optimizations to the current scrolling mechanism so that it can be smooth enough. In some cases it skips parts of the scrolling, and in other cases it skips the animation all together. All of this during a 1 second timeframe. On the other hand, the `animateScrollBy` does not have these optimizations.

With that being said, the `animateScrollToItem` will porbably cover most use cases for the users of this library and is sufficient enough, without the need to specify additional parameters passed in correctly by the user such as the `itemSize` or `density`.

Thank you for your suggestion, I really appreciate your time and effort in making this library better.
